#Configuration file for the IPERF module
iperf_client:
  total_repetition: 1
  output_iperf_dir: ./modules/iperfClient/iPerfMeasurements/
  result_measurement_filename: measurement_
  parallel_connections: 1
  destination_server_ip: 192.168.1.19
  destination_server_port: 5201
  transport_protocol: TCP
  reverse: False
  verbose: False