mongo:
  ip_server:  127.0.0.1 #192.168.1.123 #127.0.0.1 #192.168.1.123 #192.168.43.210
  port_server: 27017
  user: measurex
  password: measurex
  db_name: measurex
  measurements_collection_name: measurements
  results_collection_name: results