# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from modules.restAPIModule.swagger_server.models.base_model_ import Model
from modules.restAPIModule.swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, msg: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param msg: The msg of this InlineResponse200.  # noqa: E501
        :type msg: str
        """
        self.swagger_types = {
            'msg': str
        }

        self.attribute_map = {
            'msg': 'msg'
        }
        self._msg = msg

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg(self) -> str:
        """Gets the msg of this InlineResponse200.


        :return: The msg of this InlineResponse200.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this InlineResponse200.


        :param msg: The msg of this InlineResponse200.
        :type msg: str
        """

        self._msg = msg
