# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from modules.restAPIModule.swagger_server.models.base_model_ import Model
from modules.restAPIModule.swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, result: str=None, timestamp: str=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param id: The id of this InlineResponse2002.  # noqa: E501
        :type id: str
        :param result: The result of this InlineResponse2002.  # noqa: E501
        :type result: str
        :param timestamp: The timestamp of this InlineResponse2002.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'id': str,
            'result': str,
            'timestamp': str
        }

        self.attribute_map = {
            'id': 'id',
            'result': 'result',
            'timestamp': 'timestamp'
        }
        self._id = id
        self._result = result
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2002.


        :return: The id of this InlineResponse2002.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2002.


        :param id: The id of this InlineResponse2002.
        :type id: str
        """

        self._id = id

    @property
    def result(self) -> str:
        """Gets the result of this InlineResponse2002.


        :return: The result of this InlineResponse2002.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this InlineResponse2002.


        :param result: The result of this InlineResponse2002.
        :type result: str
        """

        self._result = result

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this InlineResponse2002.


        :return: The timestamp of this InlineResponse2002.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this InlineResponse2002.


        :param timestamp: The timestamp of this InlineResponse2002.
        :type timestamp: str
        """

        self._timestamp = timestamp
