#Configuration file for the Coordinator MQTT module

mqtt_client:
  client_id: coordinator
  clean_session: True # When this option is true, the broker automatically deletes all the subscription topics when a client logout from it.

  broker:
    host: 131.114.72.254 # 192.168.1.51
    port: 8080 # This port is beacause the opened ports on the prof's VM are 80, 22 and 8080 only.
    keep_alive: 60 # Every 60 seconds, the paho-mqtt client automatically send a keep-alive-msg to the broker
    login: True # per l'utilizzo delle credenziali, metti a True. L'ESP32 non supporta le credenziali!

  credentials:
    username: coordinator
    password: Penna3mg$

  subscription_topics:
    - "probes/+/status"
    - "probes/+/errors"
    - "probes/+/results"

  publishing:
    topics:
      commands: "probes/PROBE_ID/commands"
    qos: 0
    retain: False