#Configuration file for the Coordinator MQTT module

mqtt_client:
  client_id: coordinator
  clean_session: True # Auto-eliminazione delle subscriptions

  broker:
    host: 131.114.72.254 # 192.168.1.51
    port: 8080
    keep_alive: 60
    login: True # per l'utilizzo delle credenziali, metti a True. L'ESP32 non supporta le credenziali!

  credentials:
    username: coordinator
    password: Penna3mg$

  subscription_topics:
    - "probes/+/status"
    - "probes/+/error"
    - "probes/+/msg"

  publishing:
    probes_command_topic: "probes/PROBE_ID/commands"
    qos: 0
    retain: False