{
 "title": "MeasureX",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "selected_msm_id", "label": "Selected ID", "query": "6926c551bfb41640d732bd85" }
  ]
 },
 "panels": [
  {
   "title": "Measurements Results",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"measure-list-container\">\n  <table class=\"measure-table\" id=\"my-aoi-table\">\n    <thead>\n      <tr>\n        <th>Time</th>\n        <th>Type</th>\n      </tr>\n    </thead>\n    <tbody>\n      {{#each data}}\n      <tr class=\"clickable-row row-{{this.type}}\" data-id=\"{{this.id}}\">\n        <td>{{date this.time \"YYYY-MM-DD HH:mm:ss\"}}</td>\n        <td><span class=\"badge badge-{{this.type}}\">{{this.type}}</span></td>\n      </tr>\n      {{/each}}\n    </tbody>\n  </table>\n</div>"
   },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$and\": [\n          { \"$gte\": [\"$timestamp_iso\", { \"$dateTrunc\": { \"date\": { \"$toDate\": { \"$toLong\": \"$__from\" } }, \"unit\": \"second\" } }] },\n          { \"$lt\": [\"$timestamp_iso\", { \"$dateTrunc\": { \"date\": { \"$toDate\": { \"$toLong\": \"$__to\" } }, \"unit\": \"second\" } }] }\n        ]\n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": \"$timestamp_iso\",\n      \"type\": \"$type\",\n      \"id\": { \"$toString\": \"$msm_id\" }\n    }\n  },\n  { \"$sort\": { \"time\": -1 } }\n]"
    }
   ]
  },
  { "title": "AoI Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "AoI Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"] \n      }\n    }\n  },\n  { \"$unwind\": \"$aois\" },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": { \"$toDate\": { \"$multiply\": [\"$aois.Timestamp\", 1000] } },\n      \"instant_AoI\": \"$aois.AoI\"\n    }\n  },\n  { \"$sort\": { \"time\": 1 } }\n]"
    }
   ]
  },
  {
   "title": "AoI Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"] \n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"Max AoI\": \"$aoi_max\",\n      \"Min AoI\": \"$aoi_min\"\n    }\n  }\n]"
    }
   ]
  },
  { "title": "Latency Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"]\n      }\n    }\n  },\n  { \"$unwind\": \"$icmp_replies\" },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": {\n        \"$toDate\": {\n          \"$add\": [\n            { \"$toLong\": \"$timestamp_iso\" },\n            { \"$multiply\": [\"$icmp_replies.icmp_seq\", 1000] }\n          ]\n        }\n      },\n      \"RTT_ms\": \"$icmp_replies.time\"\n    }\n  },\n  { \"$sort\": { \"time\": 1 } }\n]"
    }
   ]
  },
  {
   "title": "Latency Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"] \n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"Avg RTT\": \"$rtt_avg\",\n      \"Max RTT\": \"$rtt_max\",\n      \"Min RTT\": \"$rtt_min\",\n      \"Packet Loss\": \"$packets_loss_rate\"\n    }\n  }\n]"
    }
   ]
  },
  { "title": "Throughput Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Throughput Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"] \n      }\n    }\n  },\n  { \"$unwind\": \"$full_result.intervals\" },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": {\n        \"$toDate\": {\n          \"$add\": [\n            { \"$toLong\": { \"$toDate\": \"$timestamp_iso\" } },\n            { \"$multiply\": [{ \"$toDouble\": \"$full_result.intervals.sum.start\" }, 1000] }\n          ]\n        }\n      },\n      \"Mbps\": {\n        \"$divide\": [{ \"$toDouble\": \"$full_result.intervals.sum.bits_per_second\" }, 1000000]\n      }\n    }\n  },\n  { \"$sort\": { \"time\": 1 } }\n]"
    }
   ]
  },
  {
   "title": "Throughput Stats ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$expr\": {\n        \"$eq\": [{ \"$toString\": \"$msm_id\" }, \"${selected_msm_id:raw}\"] \n      }\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"Average Speed\": \"$avg_speed\",\n      \"Total Data\": \"$bytes_received\"\n    }\n  }\n]"
    }
   ]
  }
 ]
}