- name: Setup Raspberry Pi Coordinator
  hosts: coordinator
  become: yes
  vars:
    path_base: "/home/{{ inventory_hostname }}/measureX"

  tasks:
    - name: Install pip and virtualenv if not already installed
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present

    - name: Create a virtual environment named measurex_venv
      command:
        cmd: python3 -m venv /home/{{ inventory_hostname }}/measurex_venv
        creates: /home/{{ inventory_hostname }}/measurex_venv

    - name: Install dependencies from requirements.txt into virtualenv
      pip:
        requirements: "{{ path_base }}/requirements.txt"
        virtualenv: "/home/{{ inventory_hostname }}/measurex_venv"
        state: present

    - name: Import MongoDB GPG key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 7F0CEB10
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        pkg: mongodb-org
        state: latest
        update_cache: yes

    - name: Install MongoDB client
      apt:
        name: mongodb-org-shell
        state: present

    - name: Enable and start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Create MongoDB user for measurex
      command: >
        mongo admin --eval "db.createUser({
          user: 'measurex',
          pwd: 'measurex',
          roles: [{ role: 'readWrite', db: 'measurexDB' }]
        })"
      ignore_errors: yes