- name: Pull latest changes from Git repository
  hosts: all
  become: yes
  tasks:
    - name: Pull latest changes using GitHub token
      command: git pull https://github.com/InternetMeasurements/measure-x.git
      args:
        chdir: "/home/{{ ansible_user }}/measureX"
    - name: Change ownership of the measureX directory to ansible_user
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/measureX"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
