---
- name: Setup virtual environment, install dependencies, and probes' software; configure probes
  hosts: all 
  become: yes
  vars_files:
    - vars.yaml	
    
  vars:
    path_base: "/home/{{ ansible_user }}/measureX/probesFirmware"
    mqtt_broker_host: "{{ MQTT_BROKER_HOST }}"
    mqtt_broker_port: "{{ MQTT_BROKER_PORT }}"
    mqtt_client_username: "{{ MQTT_BROKER_USERNAME }}"
    mqtt_client_password: "{{ MQTT_BROKER_PASSWORD }}"

  tasks:
    - name: Install pip, virtualenv, and tcpreplay if not already installed
      apt:
        name:
          - python3-pip
          - python3-venv
          - tcpreplay
        state: present

    - name: Create a virtual environment named measurex_venv
      command:
        cmd: python3 -m venv /home/{{ ansible_user }}/measurex_venv
        creates: /home/{{ ansible_user }}/measurex_venv

    - name: Set the privilege level
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/measurex_venv
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
        state: directory

    - name: Iperf3 installation
      apt:
        name: iperf3
        state: present
        update_cache: yes

    - name: git clone measure-x repository
      git:
        repo: "https://github.com/InternetMeasurements/measure-x.git"
        dest: "/home/{{ ansible_user }}/measureX"
        version: "main"
        force: yes
  
    - name: Install dependencies from requirements.txt into virtualenv
      pip:
        requirements: "{{ path_base }}/requirements.txt"
        virtualenv: "/home/{{ ansible_user }}/measurex_venv"
        state: present
  
    - name: Change ownership of the measureX directory to ansible_user
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/measureX"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
    
    - name: Sets probe id
      shell: echo probe_id{{':'}} $(hostname) > /home/{{ ansible_user }}/measureX/probesFirmware/probe_config.yaml
      args:
        creates: /home/{{ ansible_user }}/measureX/probesFirmware/probe_config.yaml

    - name: Customize and copy the mqtt client configuration
      template:
        src: probe_mqtt_client_config.j2
        dest: /home/{{ ansible_user }}/measureX/probesFirmware/mqttModule/probe_mqtt_client_config.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
    
    - name: Copy the mosquitto.crt file
      copy:
        src: mosquitto.crt
        dest: /home/{{ ansible_user }}/measureX/probesFirmware/mqttModule/mosquitto.crt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Enables I2C interface
      ansible.builtin.command:
        cmd: sudo raspi-config nonint do_i2c 0
    
    - name: Gather kernel version
      ansible.builtin.shell: uname -r
      register: kernel_release

    - name: Download and install waveshare kernel
      shell: wget -O - https://files.waveshare.com/wiki/PCIe-TO-5G-HAT%2B/install.sh | sudo bash
      args:
        chdir: "/home/{{ ansible_user }}"
      when: kernel_release.stdout != "6.6.23-v8-16k-waveshare+"
