- name: Start the firmware into virtualenv
  hosts: probes
  vars:
    venv_path: "/home/{{ ansible_user }}/measurex_venv"
  tasks:
    - name: Execute the firmware
      command: "{{ venv_path }}/bin/python3 firmware.py"
      args:
        chdir: "/home/{{ ansible_user }}/measureX/probesFirmware"
