- name: Starts the firmware on all the probes
  hosts: probes
  become: true
  become_user: "{{ ansible_user }}"
  vars:
    venv_path: "/home/{{ ansible_user }}/measurex_venv"
  tasks:
    - name: Execute the firmware
      command: "{{ venv_path }}/bin/python3 firmware.py -dbg"
      args:
        chdir: "/home/{{ ansible_user }}/measureX/probesFirmware"
