#Configuration file for the IPERF module
iperf_client:
  total_repetition: 10
  output_iperf_dir: iPerfMeasurements
  result_measurement_filename: measurement_
  parallel_connections: 2
  transport_protocol: TCP
  reverse: False
  verbose: False
  save_result_on_flash: False